[shell]
program = "/bin/zellij"

[window]
position = "None"
decorations = "Full"
opacity = 0.8
blur = false

[font]
# The normal (roman) font face to use.
normal = { family = "FiraCode Nerd Font", style = "Regular" }

# The bold font face.
bold = { family = "FiraCode Nerd Font", style = "Bold" }

# The italic font face.
italic = { family = "FiraCode Nerd Font", style = "Italic" }

# Font size in points.
size = 16.0

# Extra spacing around each character. Adjust if alignment seems off.
offset = { x = 0, y = 0 }

# Fine-tune glyph locations within their cells.
glyph_offset = { x = 0, y = 0 }

